name: Java CI & Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Permissions nécessaires pour pousser la documentation
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  quality-and-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # 1. Code Style & Static Analysis
      - name: Code Style & Static Analysis
        run: mvn clean compile checkstyle:check

      # 2. Unit Tests
      - name: Run Unit Tests
        run: mvn test
#
#      # 3. Génération de la Documentation (Javadoc)
#      - name: Generate Javadoc
#        run: mvn javadoc:javadoc
#
#      # 4. Déploiement de la documentation
#      # Se déclenche uniquement sur un push vers la branche 'master'
#      - name: Deploy Javadoc to gh-pages
#        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
#        uses: peaceiris/actions-gh-pages@v4
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./target/site/apidocs
#          publish_branch: gh-pages
#          force_orphan: true